### ISSUE TITLE
not working authentication with google to host! How config redis to .env?

### ISSUE THREAD

**Issue by bep40tv** [EyuCoder/chatgpt-clone#11]
Help me!

**Comment by EyuCoder** [comment]
just try the local_setup branch if you're having trouble

**Comment by EyuCoder** [comment]
i use ioredis BTW

**Comment by bep40tv** [comment]
> i use ioredis BTW

How use ioredis? Where can I install? How get key API user and pass?

**Comment by aliasgharheidaricom** [comment]
today it returns error 500, please double check ,it not works anymore

**Comment by EyuCoder** [comment]
> today it returns error 500, please double check ,it not works anymore

thanks. its working now
