### ISSUE TITLE
using the latest chatGPT API

### ISSUE THREAD

**Issue by staywithme23** [EyuCoder/chatgpt-clone#13]
is there any plan to use the latest chatGPT API?

**Comment by EyuCoder** [comment]
You only need to change the AI model name. **text-davinci-003** to **gpt-3.5-turbo** and you're done

**Comment by rossman22590** [comment]
did this work for you @staywithme23 ? If so i will try.

**Comment by wii8369** [comment]
I tried clicking the ChatGPT or Dell.E button on the web page, but I still can't access the ChatGPT database after entering text. The gpt-3.5-turbo model has been changed.

**Comment by EyuCoder** [comment]
i will update it to the new chatgpt api

**Comment by EyuCoder** [comment]
@staywithme23 updated to the new chatgpt api
