### ISSUE TITLE
404 Error on Windows with git checkout local_setup

### ISSUE THREAD

**Issue by kneelesh48** [EyuCoder/chatgpt-clone#15]
I `git checkout local_setup` and ran cd client && npm run dev on Windows

ChatGPT never responds and I got this error when I checked Chrome console
http://localhost:3000/davinci 404 (Not Found)

Please help

**Comment by kneelesh48** [comment]
I have only provided OpenAI API key, no redis or firebase creds

**Comment by EyuCoder** [comment]
The **openai** library is updated make sure to run `npm install` inside the server folder before you run

**Comment by kneelesh48** [comment]
I got this error

`Unsupported engine {
  package: 'server@1.0.0',
  required: { node: 'v18.12.1' },
  current: { node: 'v18.13.0', npm: '8.19.3' }
}`

I fixed it by changing the node version in package.json

But you should probably not pin it to a specific version of node

**Comment by kneelesh48** [comment]
It's still not working after running `npm install` in the server folder.
Heres a screenshot of the error in Chrome console
![image](https://user-images.githubusercontent.com/25109737/224055947-11bcf92c-f420-4e5d-8d6b-95fc80264e59.png)

**Comment by EyuCoder** [comment]
Use the main btanch i updated it to work with local storage for keys, and no backend code.
