### ISSUE TITLE
"Thinking..." don't have any answers.

### ISSUE THREAD

**Issue by wii8369** [EyuCoder/chatgpt-clone#16]
The installation is complete. Select ChatGPT/Dell.e and enter text. Question text can be generated. But the words and graphics of "Thinking..." don't have any answers.

**Comment by EyuCoder** [comment]
The **openai** library is updated make sure to run `npm install` inside the server folder before you run

**Comment by Alorse** [comment]
In my case the problem was that is was running client and server concurrently and server was in POST 3001 and my client in 3000.
I had to add my client URL to REACT_APP_BASE_URL to client/.env and run both individually

**Comment by EyuCoder** [comment]
Also try running server n client separately. env variable might not work when running concurrently

**Comment by lluangrath** [comment]
I noticed on line 81 the response is being retrieved using:
`response.data.choices[0].text`

To see the openai response change it to:
`response.data.choices[0].message.content`

Hope that helps.

**Comment by mr-wh1tehat** [comment]
Hey there I am having the same problem here("thinking"... And no response) . Let me be more precise:
I am using local_setup branch.

I am running server/backend on render.com
Frontend: on netlify
Build command i used on netlify: npm run build. 
The fronted loaded. 
I think I am making mistake when using base url. In my case now, I set it to: REACT_APP_BASE_URL : "https://mybackendserurl.onrender.com/ 
And no port i specified. Should I also specify a port?

**Comment by EyuCoder** [comment]
fixed
