### ISSUE TITLE
Remember previous conversations

### ISSUE THREAD

**Issue by RobbyV2** [EyuCoder/chatgpt-clone#21]
It would be nice for ChatGPT to remember the past questions and answers.

**Comment by EyuCoder** [comment]
Sure. will be adding that soon

**Comment by RobbyV2** [comment]
Also, if it isn't too much trouble could you add it to the local_setup branch? Thank you for the quick reply!

**Comment by EyuCoder** [comment]
sure bud

**Comment by namastexlabs** [comment]
any updates on being able to remember the chat context?

**Comment by EyuCoder** [comment]
thinkin about moving this project to nextjs so that its easier to maintain, deploy and i will do regular updates on it

**Comment by williamhuybui** [comment]
How would you build the logic behind it since there is a rate limit on how many token can be sent?

**Comment by EyuCoder** [comment]
you can use  some tokenizer package to calculate the amount of words you send. am try that and let y'all know

**Comment by EyuCoder** [comment]
added this feature to the main branch. created a `promptBuilder `that calculates **token size** before sending
