### ISSUE TITLE
length of each message not feasible

### ISSUE THREAD

**Issue by aliasgharheidaricom** [EyuCoder/chatgpt-clone#27]
it seems you limited the length of each prompt, it is not practical for English proofing texts and research, can you please return it to its initial form?

**Comment by aliasgharheidaricom** [comment]
well, but that function does not work for your website, my prompts never could run "continue" function? please tell me what is its prompt that i you mean people use?

**Comment by EyuCoder** [comment]
i hear you. i will think about it. am also thinking of ways making this app easier to use and or deploy for users
