### ISSUE TITLE
conversational context usage

### ISSUE THREAD

**Issue by Cfomodz** [EyuCoder/chatgpt-clone#32]
The reason I wanted to make a web-based clone was to have the functionality of the web app but use my own API key, however, it appears that every message sends a new chat completion request, ignoring the rest of the conversation.

If this was Python I would be happy to do it myself and provide the code - obviously, it's expensive to send the entire conversation back and forth but it should at least be an option. Otherwise, it would seem more genuine to present the user with UI that conveys this fact - such as a single input & response field, and then a "new chat" begins after that, since that is what is happening on the backend.

**Comment by EyuCoder** [comment]
Will give it a big upgrade one of this days
