### ISSUE TITLE
gpt-4

### ISSUE THREAD

**Issue by Cfomodz** [EyuCoder/chatgpt-clone#33]
Although I understand they just generally released the API access yesterday, I understand that by the end of the month, everyone using the API will have access to it. With that in mind, it seems like it would make sense to allow that as a model selection. While we're at it, would there be any reason that we wouldn't add in a few models in there?

**Comment by EyuCoder** [comment]
You're right. I was also thinking of completely rewriting it from scratch. Better ui and more models.
