### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by fanlixin** [EyuCoder/chatgpt-clone#6]
HI there, I followed the instruction to run "npm run dev" and got the following error message: 

npm run dev

> react-template@1.0.1 dev
> concurrently "npm start" "npm run server"

[0]
[0] > react-template@1.0.1 start
[0] > react-scripts start
[0]
[1]
[1] > react-template@1.0.1 server
[1] > nodemon server/server.js
[1]
[1] 'nodemon' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
[1] ���������ļ���
[1] npm run server exited with code 1

==============================
the app did't start properly and stopped with a blank screen ... 

Wonder if anyone happen to know how to fix it?  Thanx in advance.

**Comment by EyuCoder** [comment]
make sure you install the packages in server folder
`cd server && npm i`

**Comment by fanlixin** [comment]
Yes, I did run npm install in server folder.   That does not solve the problem. 

=====
npm install
cd server 
npm install 
cd ..
npm run dev 
======
end up with the reported issue. 

These funny characters in error message didn't help much.

**Comment by jaykeerti** [comment]
@fanlixin what error do you get now?

**Comment by EyuCoder** [comment]
I have completely updated the app pull the new changes and read the README instructions. hope this helps
