### ISSUE TITLE
built ok but one issue

### ISSUE THREAD

**Issue by rossman22590** [EyuCoder/chatgpt-clone#9]
localhost/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
:3000/dalle:1          Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
localhost/:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
3localhost/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

Server is running on port 3001

![screenshot-nimbusweb me-2023 01 31-14_01_49](https://user-images.githubusercontent.com/6137292/215857125-c79b6cc6-1ca4-4373-9595-f96494f27ab3.png)

frontend port 3000

i get issue after submitting any text, otherwise website loads fine

**Comment by rossman22590** [comment]
how can i fix this?

**Comment by rossman22590** [comment]
env is ok, what is Base URL in client env?

**Comment by EyuCoder** [comment]
hey guys, i tried to recreate the errors you're facing but everything is working on my side. so make sure to run them separately (dotenv sometimes doesnt work when run concurrently) and send me the error displayed on the server side.

**Comment by rossman22590** [comment]
SERVER - https://gpt-and-dalle.onrender.com/

Front End - https://new-chat-ui-gpt.vercel.app/

somethings wrong when chatting

**Comment by rossman22590** [comment]
https://gpt-and-dalle.onrender.com/dalle says something about rate limits

**Comment by EyuCoder** [comment]
> https://gpt-and-dalle.onrender.com/dalle says something about rate limits

use the local_setup branch for easier setup without redis and firebase

**Comment by rossman22590** [comment]
SOLVED!

**Comment by EyuCoder** [comment]
edited the link as requested

**Comment by rossman22590** [comment]
thank you!

**Comment by rossman22590** [comment]
i got this working with RENDER and VERCEL Successfully!!! REDIS IS SUPER IMPORTANT !
